redirects:
  previous-connectors/close: connectors/close/README.md
  previous-connectors/copper: connectors/copper/README.md
  connectors/memberstack/tutorials: connectors/memberstack/README.md
  previous-connectors/zoho-crm: connectors/zoho-crm.md
